name: Qt-old on multiple platforms

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main", "master" ]
  # pull_request:
  #   branches: [ "main", "master" ]

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }} # 指定运行环境，使用矩阵变量os
    strategy: # 定义构建策略
      fail-fast: false # 设置fail-fast为false，即使矩阵中一个任务失败，其他任务也会继续执行
      matrix:  # 定义矩阵策略，用于创建多个构建配置组合
        os: [ubuntu-latest, windows-latest]
        c_compiler: [gcc, clang, cl]
        include: # 包含特定组合的列表（精确控制矩阵）
          # Windows + MSVC
          - os: windows-latest
            triplet: x64-windows-msvc-static-release
            c_compiler: cl
            cpp_compiler: cl
            generator: "Visual Studio 17 2022"
            arch: "x64"
          # Windows + MinGW
          - os: windows-latest
            triplet: x64-windows-mingw-static-release
            c_compiler: gcc
            cpp_compiler: g++
            generator: "MinGW Makefiles"
          # Linux + GCC
          - os: ubuntu-latest
            triplet: x64-linux-gcc-static-release
            c_compiler: gcc
            cpp_compiler: g++
            generator: "Unix Makefiles"
          # Linux + Clang
          - os: ubuntu-latest
            triplet: x64-linux-clang-static-release
            c_compiler: clang
            cpp_compiler: clang++
            generator: "Unix Makefiles"
        exclude: # 排除不需要的组合
          # 排除 Windows + Clang
          - os: windows-latest
            c_compiler: clang
          # 排除 Ubuntu + MSVC
          - os: ubuntu-latest
            c_compiler: cl

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 使用actions/checkout动作检出代码库

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
            # github workspace path
            workspace_dir="${{ github.workspace }}"       # 从GitHub上下文获取路径并标准化
            workspace_dir="${workspace_dir//\\//}"        # 替换所有反斜杠为正斜杠
            workspace_dir="${workspace_dir%/}"            # 移除路径末尾的斜杠（若有）

            # release output path
            full_version="v6.10.0-$(date +'%Y%m%d').${{ github.run_number }}" # 使用语义化版本+日期+构建号
            platform=$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')-$(uname -m) # short_os-arch
            if [ "$RUNNER_OS" == "Linux" ]; then
              toolchain="${{ matrix.c_compiler }}"
            elif [ "$RUNNER_OS" == "Windows" ]; then
              if [ "${{ matrix.c_compiler }}" == "cl" ]; then
                toolchain="msvc"
              else
                toolchain="mingw"
              fi
            fi
            release_dir_name="qt-widget-${full_version}-${platform}-${toolchain}"

            # github actions env
            echo "WORKSPACE_DIR=$workspace_dir" >> "$GITHUB_OUTPUT"
            echo "RELEASE_DIR_NAME=$release_dir_name" >> "$GITHUB_OUTPUT"

            # debug output
            echo "=== GITHUB_OUTPUT ==="
            cat "$GITHUB_OUTPUT"

      - name: Download Sources
        shell: bash
        run: |
          curl -k -L --retry 3 --connect-timeout 30 -O https://download.qt.io/official_releases/qt/6.10/6.10.0/single/qt-everywhere-src-6.10.0.tar.xz
          tar -xvf qt-everywhere-src-6.10.0.tar.xz
          mv qt-everywhere-src-6.10.0 qt-src
          mkdir -p ${{ steps.strings.outputs.RELEASE_DIR_NAME }}

      - name: Configure CMake project for Release
        shell: bash
        run: |
          # 对于 Visual Studio 额外指定架构，且不在生成阶段指定 -DCMAKE_BUILD_TYPE ，而是在 Build 阶段指定 --config 参数
          # -B <build-dir> -G <generator-name> -S <source-dir> -DCMAKE_INSTALL_PREFIX=<install-dir> -DCMAKE_BUILD_TYPE=<type> -A <arch for vs>
          
          if [[ "${{ matrix.c_compiler }}" == "cl" ]]; then
            # MSVC - 多配置生成器
            cmake -B ${{ steps.strings.outputs.WORKSPACE_DIR }}/build \
            -G "${{ matrix.generator }}" \
            -S ${{ steps.strings.outputs.WORKSPACE_DIR }}/qt-src \
            -DCMAKE_INSTALL_PREFIX=${{ steps.strings.outputs.RELEASE_DIR_NAME }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -A ${{ matrix.arch }}
          else
            # 其他编译器 - 单配置生成器，先配置Release
            cmake -B ${{ steps.strings.outputs.WORKSPACE_DIR }}/build-release \
            -G "${{ matrix.generator }}" \
            -S ${{ steps.strings.outputs.WORKSPACE_DIR }}/qt-src \
            -DCMAKE_INSTALL_PREFIX=${{ steps.strings.outputs.RELEASE_DIR_NAME }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_BUILD_TYPE=Release
          fi

      - name: Configure CMake project for Debug
        shell: bash
        run: |
          # 仅为单配置生成器配置Debug版本
          if [[ "${{ matrix.c_compiler }}" != "cl" ]]; then
            cmake -B ${{ steps.strings.outputs.WORKSPACE_DIR }}/build-debug \
            -G "${{ matrix.generator }}" \
            -S ${{ steps.strings.outputs.WORKSPACE_DIR }}/qt-src \
            -DCMAKE_INSTALL_PREFIX=${{ steps.strings.outputs.RELEASE_DIR_NAME }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_BUILD_TYPE=Debug
          fi

      - name: Build And Install project
        shell: bash
        run: |
          if [[ "${{ matrix.c_compiler }}" == "cl" ]]; then
            # Visual Studio: 分别构建 Debug 和 Release (VS 需要 --config 参数，MinGW 和 Unix Makefiles 不需要 --config)
            cmake --build ${{ steps.strings.outputs.WORKSPACE_DIR }}/build --target install --config Release --parallel
            cmake --build ${{ steps.strings.outputs.WORKSPACE_DIR }}/build --target install --config Debug --parallel
          else
            # 其他编译器: 分别构建 Release 和 Debug
            cmake --build ${{ steps.strings.outputs.WORKSPACE_DIR }}/build-release --target install --parallel 2 --verbose
            cmake --build ${{ steps.strings.outputs.WORKSPACE_DIR }}/build-debug --target install --parallel 2 --verbose
          fi

      - name: Package
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            7z a -r ${{ steps.strings.outputs.WORKSPACE_DIR }}/${{ steps.strings.outputs.RELEASE_DIR_NAME }}.7z ${{ steps.strings.outputs.RELEASE_DIR_NAME }}
          else
            tar -cJvf ${{ steps.strings.outputs.WORKSPACE_DIR }}/${{ steps.strings.outputs.RELEASE_DIR_NAME }}.tar.xz ${{ steps.strings.outputs.RELEASE_DIR_NAME }}
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qt-widget-${{ matrix.os }}-${{ matrix.c_compiler }}
          path: |
            ${{ steps.strings.outputs.WORKSPACE_DIR }}/${{ steps.strings.outputs.RELEASE_DIR_NAME }}.tar.xz
            ${{ steps.strings.outputs.WORKSPACE_DIR }}/${{ steps.strings.outputs.RELEASE_DIR_NAME }}.7z
